name: Build Mod

permissions:
  contents: write

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '26'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          rm -f build/libs/*.jar
          ./gradlew build

      - name: Extract Version
        id: get_version
        run: echo "VERSION=$(./gradlew properties -q | grep '^version:' | awk '{print $2}')" >> $GITHUB_ENV

      - name: Create GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          files: build/libs/*[!dev][!sources].jar
          draft: false
          prerelease: false